// Emits src/ui/clicky.css from scripts/ui/clicky.config.json using the clicky-button engine.
// Usage: node scripts/ui/gen-clicky.mjs            (writes src/ui/clicky.css)
//        node scripts/ui/gen-clicky.mjs --check    (exits 1 when the committed file is stale)
// The engine path defaults to ~/Projects/clicky-button; override with CLICKY_BUTTON_DIR.
// Output is a pure function of (config, engine version): no clock, no randomness.
import { readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const engineDir = process.env.CLICKY_BUTTON_DIR ?? join(homedir(), 'Projects', 'clicky-button');
const engine = await import(pathToFileURL(join(engineDir, 'lib', 'clicky-button.js')).href);
const engineVersion = JSON.parse(readFileSync(join(engineDir, 'package.json'), 'utf8')).version;
const config = JSON.parse(readFileSync(join(here, 'clicky.config.json'), 'utf8'));

/**
 * The engine's toggle mode keys off a hidden checkbox (label > input:checked). The console needs a
 * real <button aria-pressed> instead, so every checkbox selector is rewritten to the equivalent
 * aria-pressed selector. The rewrite is exhaustive or the script fails: any leftover `input:`
 * pseudo-selector means the engine emitted a form this table does not know.
 */
function checkboxToAriaPressed(css) {
  const T = String.raw`(\.clicky-toggle(?:\.toggle-did-interact)?)`;
  const rules = [
    [new RegExp(`${T} input:checked ~ `, 'g'), `$1[aria-pressed='true'] `],
    [new RegExp(`${T} input:not\\(:checked\\) ~ `, 'g'), `$1[aria-pressed='false'] `],
    [/:not\(:has\(input:checked\)\)/g, `[aria-pressed='false']`],
    [/:has\(input:checked\)/g, `[aria-pressed='true']`],
    [new RegExp(`:has\\(${T} input:checked\\)`, 'g'), `:has($1[aria-pressed='true'])`],
    [new RegExp(`:has\\(${T} input:focus-visible\\)`, 'g'), `:has($1:focus-visible)`],
  ];
  let out = css;
  for (const [from, to] of rules) out = out.replace(from, to);
  const leftover = out.split('\n').filter((l) => /input:/.test(l));
  if (leftover.length > 0) {
    throw new Error(`unrewritten checkbox selectors:\n${leftover.join('\n')}`);
  }
  return out;
}

/**
 * Every rule the engine gates behind (hover: hover) is mirrored, ungated, onto :focus-visible, so a
 * keyboard user gets the same lift a pointer user gets (hover alone is invisible to touch and keyboard).
 */
function mirrorHoverToFocusVisible(css) {
  return css.replace(/@media \(hover: hover\) \{\n([\s\S]*?)\n\}/g, (block, inner) => {
    const mirrored = inner
      .split('\n')
      .map((line) => line.replace(/^ {2}/, '').replace(/:hover/g, ':focus-visible'))
      .join('\n');
    return `${block}\n\n/* focus-visible mirror of the (hover: hover) rules above */\n${mirrored}`;
  });
}

const toggleCss = mirrorHoverToFocusVisible(
  checkboxToAriaPressed(
    engine.buildClickyCss({ ...config.shared, ...config.toggle }, { scope: config.toggleScope }),
  ),
);
const clickCss = mirrorHoverToFocusVisible(
  engine.buildClickyCss({ ...config.shared, ...config.click }, { scope: config.clickScope }),
);

const banner =
  `/* GENERATED by scripts/ui/gen-clicky.mjs from scripts/ui/clicky.config.json\n` +
  `   (clicky-button ${engineVersion}). Do not edit; edit the config and re-run.\n` +
  `   Toggle keys are <button aria-pressed>, rewritten from the engine's checkbox selectors. */\n`;
const raw = `${banner}\n/* ---- toggle keys (${config.toggleScope}) ---- */\n${toggleCss}\n\n/* ---- click keys (${config.clickScope}) ---- */\n${clickCss}\n`;

const target = join(root, 'src', 'ui', 'clicky.css');
// Format with the repo's prettier config so the committed file is exactly what format:check expects.
const prettier = await import('prettier');
const output = await prettier.format(raw, {
  ...(await prettier.resolveConfig(target)),
  parser: 'css',
});
if (process.argv.includes('--check')) {
  const current = readFileSync(target, 'utf8');
  if (current !== output) {
    console.error('src/ui/clicky.css is stale: run node scripts/ui/gen-clicky.mjs');
    process.exit(1);
  }
  console.log('src/ui/clicky.css is current');
} else {
  writeFileSync(target, output);
  console.log(`wrote ${target} (${output.length} bytes)`);
}
