import { CanopyHeaderSchema, type CanopyHeader } from '../schema/canopy';

/** Canopy height above bare earth at a local-metre point, in metres; NaN outside the summary grid. */
export type CanopySampler = (east: number, north: number) => number;

/**
 * Bilinear sampler over the canopy bytes. Samples sit at cell centres; between the grid edge and the nearest centre the
 * edge value holds, and a point outside the grid rectangle is NaN.
 */
export function createCanopySampler(header: CanopyHeader, bytes: Uint8Array): CanopySampler {
  const { width, height, originX, originY, cellSizeM, scaleM } = header;
  const at = (x: number, y: number): number => (bytes[y * width + x] as number) * scaleM;
  return (east, north) => {
    const ex = (east - originX) / cellSizeM;
    const ey = (originY - north) / cellSizeM;
    if (!(ex >= 0 && ex <= width && ey >= 0 && ey <= height)) return Number.NaN;
    const fx = Math.min(Math.max(ex - 0.5, 0), width - 1);
    const fy = Math.min(Math.max(ey - 0.5, 0), height - 1);
    const x0 = Math.floor(fx);
    const y0 = Math.floor(fy);
    const x1 = Math.min(x0 + 1, width - 1);
    const y1 = Math.min(y0 + 1, height - 1);
    const tx = fx - x0;
    const ty = fy - y0;
    const top = at(x0, y0) * (1 - tx) + at(x1, y0) * tx;
    const bottom = at(x0, y1) * (1 - tx) + at(x1, y1) * tx;
    return top * (1 - ty) + bottom * ty;
  };
}

// The files are generated by npm run ingest:canopy, so a checkout without them yields empty globs and the summary reads
// as missing (never a build error).
const headerGlob: Record<string, string> = import.meta.glob('../../data/canopy.json', {
  query: '?url',
  import: 'default',
  eager: true,
});
const binGlob: Record<string, string> = import.meta.glob('../../data/canopy.u8', {
  query: '?url',
  import: 'default',
  eager: true,
});

export interface LoadCanopyOptions {
  readonly headerUrl?: string | undefined;
  readonly binUrl?: string | undefined;
  readonly fetchImpl?: typeof fetch;
}

async function sha256Hex(bytes: ArrayBuffer): Promise<string | null> {
  const subtle = globalThis.crypto?.subtle;
  if (!subtle) return null;
  const digest = new Uint8Array(await subtle.digest('SHA-256', bytes));
  return Array.from(digest, (b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * @displayName Canopy summary loader
 * @strategicPurpose Consumer gate for the canopy summary seam: trail curtains take their height from 100 kB of bytes instead of the 18 MB first-return raster, and a renamed field or truncated file fails here with a named reason instead of drawing curtains at a wrong height.
 * @tacticalObjective Fetches data/canopy.json and canopy.u8, parses the header with CanopyHeaderSchema, checks the byte length and the u8 sha256 (when crypto.subtle exists), and resolves to a bilinear sampler. A missing file logs one console.info and resolves to null; any other failure logs one console.error and resolves to null. Never rejects.
 */
export async function loadCanopy(options: LoadCanopyOptions = {}): Promise<CanopySampler | null> {
  const headerUrl = 'headerUrl' in options ? options.headerUrl : Object.values(headerGlob)[0];
  const binUrl = 'binUrl' in options ? options.binUrl : Object.values(binGlob)[0];
  if (headerUrl === undefined || binUrl === undefined) {
    console.info('canopy: no summary in the build; curtains stay at the minimum');
    return null;
  }
  const fetchImpl = options.fetchImpl ?? fetch;
  try {
    const headerResponse = await fetchImpl(headerUrl);
    if (!headerResponse.ok) throw new Error(`${headerUrl} returned HTTP ${headerResponse.status}`);
    const parsed = CanopyHeaderSchema.safeParse(await headerResponse.json());
    if (!parsed.success) {
      throw new Error(
        `canopy.json is invalid: ${parsed.error.issues
          .map((i) => `${i.path.map(String).join('.') || '(root)'}: ${i.message}`)
          .join('; ')}`,
      );
    }
    const header = parsed.data;
    const binResponse = await fetchImpl(binUrl);
    if (!binResponse.ok) throw new Error(`${binUrl} returned HTTP ${binResponse.status}`);
    const buffer = await binResponse.arrayBuffer();
    if (buffer.byteLength !== header.byteLength) {
      throw new Error(`canopy.u8 is ${buffer.byteLength} bytes, header says ${header.byteLength}`);
    }
    const sha = await sha256Hex(buffer);
    if (sha !== null && sha !== header.u8Sha256) {
      throw new Error(`canopy.u8 sha256 ${sha} does not match the header's ${header.u8Sha256}`);
    }
    return createCanopySampler(header, new Uint8Array(buffer));
  } catch (error) {
    console.error('canopy:', error instanceof Error ? error.message : String(error));
    return null;
  }
}
