import {
  ARCHETYPE_COUNT,
  TREE_RECORD_BYTES,
  TreesHeaderSchema,
  unpackTrees,
  type TreeRecord,
  type TreesHeader,
} from '../../scripts/ingest/trees-schema';
import { ContextTreesHeaderSchema, type ContextTreesHeader } from '../../scripts/ingest/context-trees-schema';
import { loadTerrain, type LoadedTerrain } from './load-terrain';

/** Simulated trees that loaded: the validated header and the decoded records. */
export interface LoadedTrees {
  readonly header: TreesHeader;
  readonly records: readonly TreeRecord[];
}

/** The far-field trees that loaded: the validated header and the decoded records (same record format as LoadedTrees). */
export interface LoadedContextTrees {
  readonly header: ContextTreesHeader;
  readonly records: readonly TreeRecord[];
}

export type TreesLayer = LoadedTrees | { readonly error: string };
/** The context trees layer: loaded, failed, or absent (the files are not in the build, which is not an error). */
export type ContextTreesLayer = LoadedContextTrees | { readonly error: string } | { readonly absent: true };
export type NoCanopyLayer = LoadedTerrain | { readonly error: string };

export interface TreesLoad {
  readonly trees: TreesLayer;
  /** The core heightfield with canopy cells replaced by bare earth; the mixed mode swaps the core mesh to it. */
  readonly noCanopy: NoCanopyLayer;
}

export interface TreesUrls {
  readonly treesHeader?: string;
  readonly treesBin?: string;
  readonly noCanopyHeader?: string;
  readonly noCanopyBin?: string;
}

function urlOf(glob: Readonly<Record<string, string>>, name: string): string | undefined {
  for (const [path, url] of Object.entries(glob)) {
    if (path.endsWith(`/${name}`)) return url;
  }
  return undefined;
}

// The files are generated by npm run ingest:trees, so a fresh checkout without them yields empty globs
// and the layer reads as missing (never a build error).
const jsonGlob: Record<string, string> = import.meta.glob(
  ['../../data/trees.json', '../../data/surface/core-nocanopy.json', '../../data/context-trees.json'],
  { query: '?url', import: 'default', eager: true },
);
const binGlob: Record<string, string> = import.meta.glob(
  ['../../data/trees.bin', '../../data/surface/core-nocanopy.f32', '../../data/context-trees.bin'],
  { query: '?url', import: 'default', eager: true },
);
const defaultUrls: TreesUrls = {
  ...(urlOf(jsonGlob, 'trees.json') ? { treesHeader: urlOf(jsonGlob, 'trees.json') } : {}),
  ...(urlOf(binGlob, 'trees.bin') ? { treesBin: urlOf(binGlob, 'trees.bin') } : {}),
  ...(urlOf(jsonGlob, 'core-nocanopy.json')
    ? { noCanopyHeader: urlOf(jsonGlob, 'core-nocanopy.json') }
    : {}),
  ...(urlOf(binGlob, 'core-nocanopy.f32')
    ? { noCanopyBin: urlOf(binGlob, 'core-nocanopy.f32') }
    : {}),
};

const defaultContextUrls: { header?: string; bin?: string } = {
  ...(urlOf(jsonGlob, 'context-trees.json') ? { header: urlOf(jsonGlob, 'context-trees.json') } : {}),
  ...(urlOf(binGlob, 'context-trees.bin') ? { bin: urlOf(binGlob, 'context-trees.bin') } : {}),
};

export interface LoadTreesOptions {
  readonly frameUrl: string;
  readonly urls?: TreesUrls;
  readonly fetchImpl?: typeof fetch;
}

async function sha256Hex(bytes: ArrayBuffer): Promise<string> {
  const subtle = globalThis.crypto?.subtle;
  if (!subtle) throw new Error('crypto.subtle is unavailable (needs https or localhost)');
  const digest = new Uint8Array(await subtle.digest('SHA-256', bytes));
  return Array.from(digest, (b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Parses and checks decoded records against the header: finite values, archetype ids in range, colour in 0..1,
 * height above zero. Pure, so tests need no network. Throws on the first violation.
 */
export function checkTrees(
  header: { readonly count: number },
  records: readonly TreeRecord[],
): void {
  if (records.length !== header.count) {
    throw new Error(`trees.bin holds ${records.length} records, header says ${header.count}`);
  }
  records.forEach((t, i) => {
    for (const [key, value] of Object.entries(t)) {
      if (!Number.isFinite(value)) throw new Error(`tree ${i}: ${key} is not finite`);
    }
    if (!Number.isInteger(t.type) || t.type < 0 || t.type >= ARCHETYPE_COUNT) {
      throw new Error(`tree ${i}: type ${t.type} is not an archetype id 0..${ARCHETYPE_COUNT - 1}`);
    }
    if (!(t.height > 0)) throw new Error(`tree ${i}: height ${t.height} is not positive`);
    for (const c of [t.r, t.g, t.b]) {
      if (c < 0 || c > 1) throw new Error(`tree ${i}: colour channel ${c} is outside 0..1`);
    }
  });
}

/**
 * @displayName Trees loader
 * @strategicPurpose Consumer gate for the trees seam: the browser never reads data/trees.bin from a guessed layout, and an upstream rename or truncation fails here instead of drawing a broken forest. Seam record: trees.json emitter_gate = scripts/ingest/trees.ts (TreesHeaderSchema.safeParse); consumer_gate = this file.
 * @tacticalObjective Fetches trees.json, frame.json and trees.bin; parses the header with TreesHeaderSchema, checks the frame sha256 and byte length (count * 36), decodes little-endian Float32 records and checks every value; separately loads core-nocanopy through loadTerrain. Resolves to { trees, noCanopy }, each a result or { error }. Never throws.
 */
export async function loadTrees(options: LoadTreesOptions): Promise<TreesLoad> {
  const urls = options.urls ?? defaultUrls;
  const fetchImpl = options.fetchImpl ?? fetch;
  const loadList = async (): Promise<TreesLayer> => {
    if (urls.treesHeader === undefined || urls.treesBin === undefined) {
      return { error: 'trees files are not in the build' };
    }
    try {
      const headerResponse = await fetchImpl(urls.treesHeader);
      if (!headerResponse.ok) throw new Error(`${urls.treesHeader} returned HTTP ${headerResponse.status}`);
      const parsed = TreesHeaderSchema.safeParse(await headerResponse.json());
      if (!parsed.success) {
        throw new Error(
          parsed.error.issues.map((i) => `${i.path.join('.') || '(root)'}: ${i.message}`).join('; '),
        );
      }
      const header = parsed.data;
      const frameResponse = await fetchImpl(options.frameUrl);
      if (!frameResponse.ok) throw new Error(`${options.frameUrl} returned HTTP ${frameResponse.status}`);
      const frameSha = await sha256Hex(await frameResponse.arrayBuffer());
      if (frameSha !== header.frame.sha256) {
        throw new Error(`frame.json sha256 ${frameSha} differs from the trees header ${header.frame.sha256}`);
      }
      const binResponse = await fetchImpl(urls.treesBin);
      if (!binResponse.ok) throw new Error(`${urls.treesBin} returned HTTP ${binResponse.status}`);
      const buffer = await binResponse.arrayBuffer();
      if (buffer.byteLength !== header.byteLength || buffer.byteLength !== header.count * TREE_RECORD_BYTES) {
        throw new Error(`trees.bin is ${buffer.byteLength} bytes, header says ${header.byteLength}`);
      }
      const records = unpackTrees(buffer, header.count);
      checkTrees(header, records);
      return { header, records };
    } catch (error) {
      return { error: `trees: ${error instanceof Error ? error.message : String(error)}` };
    }
  };
  const loadNoCanopy = async (): Promise<NoCanopyLayer> => {
    if (urls.noCanopyHeader === undefined || urls.noCanopyBin === undefined) {
      return { error: 'core-nocanopy files are not in the build' };
    }
    try {
      return await loadTerrain({
        headerUrl: urls.noCanopyHeader,
        binUrl: urls.noCanopyBin,
        frameUrl: options.frameUrl,
        fetchImpl,
      });
    } catch (error) {
      return { error: `core-nocanopy: ${error instanceof Error ? error.message : String(error)}` };
    }
  };
  const [trees, noCanopy] = await Promise.all([loadList(), loadNoCanopy()]);
  return { trees, noCanopy };
}

export interface LoadContextTreesOptions {
  readonly frameUrl: string;
  readonly urls?: { readonly header?: string; readonly bin?: string };
  readonly fetchImpl?: typeof fetch;
}

/**
 * @displayName Context trees loader
 * @strategicPurpose Consumer gate for the context-trees seam: the browser never reads data/context-trees.bin from a guessed layout, and a stale or truncated file fails here instead of drawing a broken far-field forest. Seam record: context-trees.json emitter_gate = scripts/ingest/context-trees.ts (ContextTreesHeaderSchema.safeParse); consumer_gate = this function.
 * @tacticalObjective Fetches context-trees.json, frame.json and context-trees.bin; parses the header with ContextTreesHeaderSchema, checks the frame sha256 and byte length (count * 36), decodes the records and checks every value. Resolves to the layer, { error } on any failure, or { absent } when the files are not in the build. Never throws.
 */
export async function loadContextTrees(
  options: LoadContextTreesOptions,
): Promise<ContextTreesLayer> {
  const urls = options.urls ?? defaultContextUrls;
  if (urls.header === undefined || urls.bin === undefined) return { absent: true };
  const fetchImpl = options.fetchImpl ?? fetch;
  try {
    const headerResponse = await fetchImpl(urls.header);
    if (!headerResponse.ok) throw new Error(`${urls.header} returned HTTP ${headerResponse.status}`);
    const parsed = ContextTreesHeaderSchema.safeParse(await headerResponse.json());
    if (!parsed.success) {
      throw new Error(
        parsed.error.issues.map((i) => `${i.path.join('.') || '(root)'}: ${i.message}`).join('; '),
      );
    }
    const header = parsed.data;
    const frameResponse = await fetchImpl(options.frameUrl);
    if (!frameResponse.ok) throw new Error(`${options.frameUrl} returned HTTP ${frameResponse.status}`);
    const frameSha = await sha256Hex(await frameResponse.arrayBuffer());
    if (frameSha !== header.frame.sha256) {
      throw new Error(
        `frame.json sha256 ${frameSha} differs from the context-trees header ${header.frame.sha256}`,
      );
    }
    const binResponse = await fetchImpl(urls.bin);
    if (!binResponse.ok) throw new Error(`${urls.bin} returned HTTP ${binResponse.status}`);
    const buffer = await binResponse.arrayBuffer();
    if (
      buffer.byteLength !== header.byteLength ||
      buffer.byteLength !== header.count * TREE_RECORD_BYTES
    ) {
      throw new Error(
        `context-trees.bin is ${buffer.byteLength} bytes, header says ${header.byteLength}`,
      );
    }
    const records = unpackTrees(buffer, header.count);
    checkTrees(header, records);
    return { header, records };
  } catch (error) {
    return { error: `context-trees: ${error instanceof Error ? error.message : String(error)}` };
  }
}
