import { PlacesFileSchema, type Place } from '../schema/places';

/**
 * @displayName Places load error
 * @strategicPurpose Makes every places.json failure a named, catchable error so a bad file is reported once and the signs fall back to "N trails" instead of throwing in the scene.
 * @tacticalObjective Carries a message naming the first problem found at the boundary.
 */
export class PlacesLoadError extends Error {
  override name = 'PlacesLoadError';
}

// The file is generated by npm run ingest:places, so a checkout without it yields an empty glob and the layer reads as absent (never a build error).
const placesGlob: Record<string, string> = import.meta.glob('../../data/places.json', {
  query: '?url',
  import: 'default',
  eager: true,
});
const defaultUrl: string | undefined = Object.values(placesGlob)[0];

export interface LoadPlacesOptions {
  /** Defaults to the bundled data/places.json URL; undefined means the file is not in the build. */
  readonly url?: string | undefined;
  readonly frameUrl: string;
  readonly fetchImpl?: typeof fetch;
  /** Defaults to console.info. */
  readonly info?: (message: string) => void;
}

async function sha256Hex(bytes: ArrayBuffer): Promise<string> {
  const subtle = globalThis.crypto?.subtle;
  if (!subtle) throw new PlacesLoadError('crypto.subtle is unavailable (needs https or localhost)');
  const digest = new Uint8Array(await subtle.digest('SHA-256', bytes));
  return Array.from(digest, (b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * @displayName Parse places file
 * @strategicPurpose Consumer gate for data/places.json (foreign-data seam; the emitter gate is scripts/ingest/places-core.ts), so a renamed field fails here and never reads as "no places".
 * @tacticalObjective Parses with PlacesFileSchema.safeParse and throws PlacesLoadError naming issues[0]; on success returns the places in file order.
 */
export function parsePlaces(raw: unknown): { places: readonly Place[]; frameSha256: string } {
  const parsed = PlacesFileSchema.safeParse(raw);
  if (!parsed.success) {
    const first = parsed.error.issues[0];
    const where = first === undefined || first.path.length === 0 ? '(root)' : first.path.join('.');
    throw new PlacesLoadError(
      `places.json failed validation at ${where}: ${first?.message ?? 'unknown issue'} (${parsed.error.issues.length} issue(s) in total)`,
    );
  }
  return { places: parsed.data.places, frameSha256: parsed.data.frame.sha256 };
}

/**
 * @displayName Load places
 * @strategicPurpose Gives the sign layer its named places. The file is optional: a build without data/places.json logs one line and labels stay "N trails".
 * @tacticalObjective Resolves to [] with one console.info when the file is not in the build. Otherwise fetches places.json and frame.json, parses the file, checks the frame sha256 it was projected with, and returns the places; throws PlacesLoadError on HTTP failure, bad JSON, a schema failure or a frame mismatch.
 */
export async function loadPlaces(options: LoadPlacesOptions): Promise<readonly Place[]> {
  const url = 'url' in options ? options.url : defaultUrl;
  const info = options.info ?? ((message: string) => console.info(message));
  if (url === undefined) {
    info('places: data/places.json is not in the build; concentration signs keep their trail counts');
    return [];
  }
  const fetchImpl = options.fetchImpl ?? fetch;
  let response: Response;
  try {
    response = await fetchImpl(url);
  } catch (cause) {
    throw new PlacesLoadError(`places.json request failed: ${String(cause)} (${url})`);
  }
  if (!response.ok) throw new PlacesLoadError(`places.json request failed: HTTP ${response.status} for ${url}`);
  let raw: unknown;
  try {
    raw = await response.json();
  } catch {
    throw new PlacesLoadError(`places.json is not valid JSON (${url})`);
  }
  const { places, frameSha256 } = parsePlaces(raw);
  const frameResponse = await fetchImpl(options.frameUrl);
  if (!frameResponse.ok) {
    throw new PlacesLoadError(`frame.json request failed: HTTP ${frameResponse.status} for ${options.frameUrl}`);
  }
  const frameSha = await sha256Hex(await frameResponse.arrayBuffer());
  if (frameSha !== frameSha256) {
    throw new PlacesLoadError(`frame.json sha256 ${frameSha} differs from the places file ${frameSha256}`);
  }
  return places;
}
