import { TreeStatsSchema, type TreeStats } from '../schema/tree-stats';

export type TreeStatsResult = TreeStats | { readonly absent: true } | { readonly error: string };

// The file is generated by npm run ingest:tree-stats, so a checkout without it yields an empty glob
// and the layer reads as absent (never a build error).
const statsGlob: Record<string, string> = import.meta.glob('../../data/tree-stats.json', {
  query: '?url',
  import: 'default',
  eager: true,
});
const defaultUrl: string | undefined = Object.values(statsGlob)[0];

/**
 * @displayName Tree statistics loader
 * @strategicPurpose Consumer gate for data/tree-stats.json: a renamed or missing field fails here with a named reason instead of tinting the ground plane with undefined or NaN, and a missing file lets the ground fall back to the imagery mean.
 * @tacticalObjective Fetches the JSON, parses it once with TreeStatsSchema, and resolves to the stats, to { absent } when the file is not in the build, or to { error }. Never rejects.
 */
export async function loadTreeStats(
  url: string | undefined = defaultUrl,
  fetchImpl: typeof fetch = fetch,
): Promise<TreeStatsResult> {
  if (url === undefined) return { absent: true };
  try {
    const response = await fetchImpl(url);
    if (!response.ok) return { error: `${url} returned HTTP ${response.status}` };
    const parsed = TreeStatsSchema.safeParse(await response.json());
    if (!parsed.success) {
      return {
        error: `tree-stats.json is invalid: ${parsed.error.issues
          .map((i) => `${i.path.map(String).join('.') || '(root)'}: ${i.message}`)
          .join('; ')}`,
      };
    }
    return parsed.data;
  } catch (error) {
    return {
      error: `could not load ${url}: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}
