import type { Texture } from 'three';
import { CONTEXT_TILES, tileKey } from '../../scripts/ingest/context-tiles';
import type { TerrainHeader } from '../schema/terrain';
import type { Heightfield } from '../scene/heightfield';
import { loadImagery } from './load-imagery';
import { loadTerrain } from './load-terrain';

/** One context tile that loaded: its header and heightfield, and the url of its NAIP jpg (null when the jpg is not pinned). */
export interface ContextTile {
  readonly i: number;
  readonly j: number;
  readonly key: string;
  readonly header: TerrainHeader;
  readonly heightfield: Heightfield;
  readonly imageryUrl: string | null;
}

export interface MissingTile {
  readonly i: number;
  readonly j: number;
  readonly key: string;
  readonly reason: string;
}

export interface ContextLoad {
  readonly tiles: ContextTile[];
  readonly missing: MissingTile[];
}

/** Url lookup by tile key. Built from import.meta.glob in production and from literals in tests. */
export interface ContextUrls {
  readonly headers: Readonly<Record<string, string>>;
  readonly bins: Readonly<Record<string, string>>;
  readonly images: Readonly<Record<string, string>>;
}

/** Maps glob results (path to url) to a tile-key lookup, keeping only files named <i>_<j>.<ext>. */
export function indexByTileKey(
  glob: Readonly<Record<string, string>>,
  ext: string,
): Record<string, string> {
  const out: Record<string, string> = {};
  const pattern = new RegExp(`(?:^|/)(-?\\d+_-?\\d+)\\.${ext}$`);
  for (const [path, url] of Object.entries(glob)) {
    const key = pattern.exec(path)?.[1];
    if (key !== undefined) out[key] = url;
  }
  return out;
}

// The tiles are generated by npm run ingest:context-terrain, so a fresh checkout without them yields empty globs
// and every tile reads as missing (never a build error).
const defaultUrls: ContextUrls = {
  headers: indexByTileKey(
    import.meta.glob('../../data/context/*.json', { query: '?url', import: 'default', eager: true }),
    'json',
  ),
  bins: indexByTileKey(
    import.meta.glob('../../data/context/*.f32', { query: '?url', import: 'default', eager: true }),
    'f32',
  ),
  images: indexByTileKey(
    import.meta.glob('../../data/raw/context/*.jpg', {
      query: '?url',
      import: 'default',
      eager: true,
    }),
    'jpg',
  ),
};

export interface LoadContextOptions {
  readonly frameUrl: string;
  readonly urls?: ContextUrls;
  /** Tiles to load; defaults to the whole tile table. */
  readonly tiles?: readonly (readonly [number, number])[];
  readonly fetchImpl?: typeof fetch;
}

/**
 * @displayName Context loader
 * @strategicPurpose Consumer gate for the context-tile seam: each tile's header, frame hash, byte length and values are checked before it is drawn, and a bad tile costs only that tile, never the centre terrain or the other tiles.
 * @tacticalObjective Loads every tile in the table through loadTerrain (TerrainHeaderSchema, FrameSchema, frame sha256, byte length, finiteness, range), and returns the tiles that loaded plus a missing list with a reason per failed tile. Never throws.
 */
export async function loadContext(options: LoadContextOptions): Promise<ContextLoad> {
  const urls = options.urls ?? defaultUrls;
  const tiles: ContextTile[] = [];
  const missing: MissingTile[] = [];
  const results: ({ tile: ContextTile } | { missing: MissingTile })[] = await Promise.all(
    (options.tiles ?? CONTEXT_TILES).map(async ([i, j]) => {
      const key = tileKey(i, j);
      const headerUrl = urls.headers[key];
      const binUrl = urls.bins[key];
      if (headerUrl === undefined || binUrl === undefined) {
        return { missing: { i, j, key, reason: 'tile files are not in the build' } };
      }
      try {
        const { header, heightfield } = await loadTerrain({
          headerUrl,
          binUrl,
          frameUrl: options.frameUrl,
          ...(options.fetchImpl ? { fetchImpl: options.fetchImpl } : {}),
        });
        return { tile: { i, j, key, header, heightfield, imageryUrl: urls.images[key] ?? null } };
      } catch (error) {
        return {
          missing: { i, j, key, reason: error instanceof Error ? error.message : String(error) },
        };
      }
    }),
  );
  for (const result of results) {
    if ('tile' in result) tiles.push(result.tile);
    else missing.push(result.missing);
  }
  return { tiles, missing };
}

export interface LoadContextTexturesOptions {
  readonly capabilities: { getMaxAnisotropy(): number; maxTextureSize: number };
  readonly onTexture: (key: string, texture: Texture) => void;
  /** Called once per tile whose jpg fails to load; that tile keeps its slope shading. */
  readonly onFailure: (key: string, reason: string) => void;
  readonly loadTexture?: (url: string) => Promise<Texture>;
}

/** Loads each tile's NAIP jpg through loadImagery (which never throws) and reports each result as it resolves. */
export async function loadContextTextures(
  tiles: readonly ContextTile[],
  options: LoadContextTexturesOptions,
): Promise<void> {
  await Promise.all(
    tiles.map(async (tile) => {
      if (tile.imageryUrl === null) {
        options.onFailure(tile.key, 'jpg is not in the build');
        return;
      }
      const result = await loadImagery({
        url: tile.imageryUrl,
        capabilities: options.capabilities,
        ...(options.loadTexture ? { loadTexture: options.loadTexture } : {}),
      });
      if (result.texture === null) options.onFailure(tile.key, result.reason);
      else options.onTexture(tile.key, result.texture);
    }),
  );
}
