import { loadTerrain, type LoadedTerrain } from './load-terrain';

/** One surface heightfield that loaded, or the reason it did not. */
export type SurfaceLayer = LoadedTerrain | { readonly error: string };

export interface SurfaceLoad {
  /** First returns over the whole terrain square at 4 m. */
  readonly square: SurfaceLayer;
  /** First returns over the 2.5 km core window at 2 m. */
  readonly core: SurfaceLayer;
}

export interface SurfaceUrls {
  readonly squareHeader?: string;
  readonly squareBin?: string;
  readonly coreHeader?: string;
  readonly coreBin?: string;
}

/** Picks the url for one file name out of a glob result (path to url). */
function urlOf(glob: Readonly<Record<string, string>>, name: string): string | undefined {
  for (const [path, url] of Object.entries(glob)) {
    if (path.endsWith(`/${name}`)) return url;
  }
  return undefined;
}

// The files are generated by npm run ingest:surface-terrain, so a fresh checkout without them yields empty globs
// and each layer reads as missing (never a build error).
const headerGlob: Record<string, string> = import.meta.glob('../../data/surface/*.json', {
  query: '?url',
  import: 'default',
  eager: true,
});
const binGlob: Record<string, string> = import.meta.glob('../../data/surface/*.f32', {
  query: '?url',
  import: 'default',
  eager: true,
});
const defaultUrls: SurfaceUrls = {
  ...(urlOf(headerGlob, 'square.json') ? { squareHeader: urlOf(headerGlob, 'square.json') } : {}),
  ...(urlOf(binGlob, 'square.f32') ? { squareBin: urlOf(binGlob, 'square.f32') } : {}),
  ...(urlOf(headerGlob, 'core.json') ? { coreHeader: urlOf(headerGlob, 'core.json') } : {}),
  ...(urlOf(binGlob, 'core.f32') ? { coreBin: urlOf(binGlob, 'core.f32') } : {}),
};

export interface LoadSurfaceOptions {
  readonly frameUrl: string;
  readonly urls?: SurfaceUrls;
  readonly fetchImpl?: typeof fetch;
}

async function loadOne(
  what: string,
  headerUrl: string | undefined,
  binUrl: string | undefined,
  options: LoadSurfaceOptions,
): Promise<SurfaceLayer> {
  if (headerUrl === undefined || binUrl === undefined) {
    return { error: `${what} files are not in the build` };
  }
  try {
    return await loadTerrain({
      headerUrl,
      binUrl,
      frameUrl: options.frameUrl,
      ...(options.fetchImpl ? { fetchImpl: options.fetchImpl } : {}),
    });
  } catch (error) {
    return { error: `${what}: ${error instanceof Error ? error.message : String(error)}` };
  }
}

/**
 * @displayName Surface loader
 * @strategicPurpose Consumer gate for the first-return surface seam: both heightfields pass the same header, frame hash, byte length, finiteness and range checks as the bare-earth terrain, and one bad file costs only its own layer.
 * @tacticalObjective Loads data/surface/square.{json,f32} and core.{json,f32} through loadTerrain and resolves to { square, core }, each either a loaded terrain or { error }. Never throws.
 */
export async function loadSurface(options: LoadSurfaceOptions): Promise<SurfaceLoad> {
  const urls = options.urls ?? defaultUrls;
  const [square, core] = await Promise.all([
    loadOne('surface square', urls.squareHeader, urls.squareBin, options),
    loadOne('surface core', urls.coreHeader, urls.coreBin, options),
  ]);
  return { square, core };
}
